const jwt = require("jsonwebtoken");
const config = require("../Config/Keys");
const { promisify } = require("util");

exports.signToken = (id) => {
  return jwt.sign(
    {
      id: id,
    },
    config.jwtSecret,
    { expiresIn: config.jwtExpiresIn }
  );
};

/**
 Id /null  - if user with the provided token exists it will return user id else it will return null
 */
exports.getUserId = async (token) => {
  // ? Verifying the token is generated by this our api.
  const { id, iat } = await promisify(jwt.verify)(token, config.jwtSecret);
  return id;
};
